// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#include "config.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace PFDESolver {
PROTOBUF_CONSTEXPR TSolverConfig::TSolverConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.spacecount_)*/uint64_t{0u}
  , /*decltype(_impl_.timecount_)*/uint64_t{0u}
  , /*decltype(_impl_.leftbound_)*/0
  , /*decltype(_impl_.rightbound_)*/0
  , /*decltype(_impl_.maxtime_)*/0
  , /*decltype(_impl_.alpha_)*/0
  , /*decltype(_impl_.gamma_)*/0
  , /*decltype(_impl_.spacestep_)*/0
  , /*decltype(_impl_.timestep_)*/0
  , /*decltype(_impl_.beta_)*/0
  , /*decltype(_impl_.alphaleft_)*/0
  , /*decltype(_impl_.betaleft_)*/0
  , /*decltype(_impl_.alpharight_)*/0
  , /*decltype(_impl_.betaright_)*/0
  , /*decltype(_impl_.bordersavailable_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TSolverConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TSolverConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TSolverConfigDefaultTypeInternal() {}
  union {
    TSolverConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TSolverConfigDefaultTypeInternal _TSolverConfig_default_instance_;
}  // namespace PFDESolver
static ::_pb::Metadata file_level_metadata_config_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_config_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_config_2eproto = nullptr;

const uint32_t TableStruct_config_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.spacecount_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.timecount_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.leftbound_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.rightbound_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.maxtime_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.alpha_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.gamma_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.spacestep_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.timestep_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.beta_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.alphaleft_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.betaleft_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.alpharight_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.betaright_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TSolverConfig, _impl_.bordersavailable_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PFDESolver::TSolverConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::PFDESolver::_TSolverConfig_default_instance_._instance,
};

const char descriptor_table_protodef_config_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014config.proto\022\nPFDESolver\"\245\002\n\rTSolverCo"
  "nfig\022\022\n\nSpaceCount\030\001 \001(\004\022\021\n\tTimeCount\030\002 "
  "\001(\004\022\021\n\tLeftBound\030\003 \001(\001\022\022\n\nRightBound\030\004 \001"
  "(\001\022\017\n\007MaxTime\030\005 \001(\001\022\r\n\005Alpha\030\006 \001(\001\022\r\n\005Ga"
  "mma\030\007 \001(\001\022\021\n\tSpaceStep\030\010 \001(\001\022\020\n\010TimeStep"
  "\030\t \001(\001\022\014\n\004Beta\030\n \001(\001\022\021\n\tAlphaLeft\030\013 \001(\001\022"
  "\020\n\010BetaLeft\030\014 \001(\001\022\022\n\nAlphaRight\030\r \001(\001\022\021\n"
  "\tBetaRight\030\016 \001(\001\022\030\n\020BordersAvailable\030\017 \001"
  "(\010b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_config_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_config_2eproto = {
    false, false, 330, descriptor_table_protodef_config_2eproto,
    "config.proto",
    &descriptor_table_config_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_config_2eproto::offsets,
    file_level_metadata_config_2eproto, file_level_enum_descriptors_config_2eproto,
    file_level_service_descriptors_config_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_config_2eproto_getter() {
  return &descriptor_table_config_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_config_2eproto(&descriptor_table_config_2eproto);
namespace PFDESolver {

// ===================================================================

class TSolverConfig::_Internal {
 public:
};

TSolverConfig::TSolverConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PFDESolver.TSolverConfig)
}
TSolverConfig::TSolverConfig(const TSolverConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TSolverConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.spacecount_){}
    , decltype(_impl_.timecount_){}
    , decltype(_impl_.leftbound_){}
    , decltype(_impl_.rightbound_){}
    , decltype(_impl_.maxtime_){}
    , decltype(_impl_.alpha_){}
    , decltype(_impl_.gamma_){}
    , decltype(_impl_.spacestep_){}
    , decltype(_impl_.timestep_){}
    , decltype(_impl_.beta_){}
    , decltype(_impl_.alphaleft_){}
    , decltype(_impl_.betaleft_){}
    , decltype(_impl_.alpharight_){}
    , decltype(_impl_.betaright_){}
    , decltype(_impl_.bordersavailable_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.spacecount_, &from._impl_.spacecount_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.bordersavailable_) -
    reinterpret_cast<char*>(&_impl_.spacecount_)) + sizeof(_impl_.bordersavailable_));
  // @@protoc_insertion_point(copy_constructor:PFDESolver.TSolverConfig)
}

inline void TSolverConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.spacecount_){uint64_t{0u}}
    , decltype(_impl_.timecount_){uint64_t{0u}}
    , decltype(_impl_.leftbound_){0}
    , decltype(_impl_.rightbound_){0}
    , decltype(_impl_.maxtime_){0}
    , decltype(_impl_.alpha_){0}
    , decltype(_impl_.gamma_){0}
    , decltype(_impl_.spacestep_){0}
    , decltype(_impl_.timestep_){0}
    , decltype(_impl_.beta_){0}
    , decltype(_impl_.alphaleft_){0}
    , decltype(_impl_.betaleft_){0}
    , decltype(_impl_.alpharight_){0}
    , decltype(_impl_.betaright_){0}
    , decltype(_impl_.bordersavailable_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TSolverConfig::~TSolverConfig() {
  // @@protoc_insertion_point(destructor:PFDESolver.TSolverConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TSolverConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TSolverConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TSolverConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:PFDESolver.TSolverConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.spacecount_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.bordersavailable_) -
      reinterpret_cast<char*>(&_impl_.spacecount_)) + sizeof(_impl_.bordersavailable_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TSolverConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 SpaceCount = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.spacecount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 TimeCount = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.timecount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double LeftBound = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.leftbound_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double RightBound = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.rightbound_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double MaxTime = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.maxtime_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double Alpha = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.alpha_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double Gamma = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.gamma_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double SpaceStep = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 65)) {
          _impl_.spacestep_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double TimeStep = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _impl_.timestep_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double Beta = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 81)) {
          _impl_.beta_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double AlphaLeft = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 89)) {
          _impl_.alphaleft_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double BetaLeft = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 97)) {
          _impl_.betaleft_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double AlphaRight = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 105)) {
          _impl_.alpharight_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double BetaRight = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 113)) {
          _impl_.betaright_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bool BordersAvailable = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          _impl_.bordersavailable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TSolverConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PFDESolver.TSolverConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 SpaceCount = 1;
  if (this->_internal_spacecount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_spacecount(), target);
  }

  // uint64 TimeCount = 2;
  if (this->_internal_timecount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_timecount(), target);
  }

  // double LeftBound = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_leftbound = this->_internal_leftbound();
  uint64_t raw_leftbound;
  memcpy(&raw_leftbound, &tmp_leftbound, sizeof(tmp_leftbound));
  if (raw_leftbound != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_leftbound(), target);
  }

  // double RightBound = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_rightbound = this->_internal_rightbound();
  uint64_t raw_rightbound;
  memcpy(&raw_rightbound, &tmp_rightbound, sizeof(tmp_rightbound));
  if (raw_rightbound != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_rightbound(), target);
  }

  // double MaxTime = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_maxtime = this->_internal_maxtime();
  uint64_t raw_maxtime;
  memcpy(&raw_maxtime, &tmp_maxtime, sizeof(tmp_maxtime));
  if (raw_maxtime != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_maxtime(), target);
  }

  // double Alpha = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alpha = this->_internal_alpha();
  uint64_t raw_alpha;
  memcpy(&raw_alpha, &tmp_alpha, sizeof(tmp_alpha));
  if (raw_alpha != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_alpha(), target);
  }

  // double Gamma = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_gamma = this->_internal_gamma();
  uint64_t raw_gamma;
  memcpy(&raw_gamma, &tmp_gamma, sizeof(tmp_gamma));
  if (raw_gamma != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_gamma(), target);
  }

  // double SpaceStep = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_spacestep = this->_internal_spacestep();
  uint64_t raw_spacestep;
  memcpy(&raw_spacestep, &tmp_spacestep, sizeof(tmp_spacestep));
  if (raw_spacestep != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(8, this->_internal_spacestep(), target);
  }

  // double TimeStep = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_timestep = this->_internal_timestep();
  uint64_t raw_timestep;
  memcpy(&raw_timestep, &tmp_timestep, sizeof(tmp_timestep));
  if (raw_timestep != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(9, this->_internal_timestep(), target);
  }

  // double Beta = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_beta = this->_internal_beta();
  uint64_t raw_beta;
  memcpy(&raw_beta, &tmp_beta, sizeof(tmp_beta));
  if (raw_beta != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(10, this->_internal_beta(), target);
  }

  // double AlphaLeft = 11;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alphaleft = this->_internal_alphaleft();
  uint64_t raw_alphaleft;
  memcpy(&raw_alphaleft, &tmp_alphaleft, sizeof(tmp_alphaleft));
  if (raw_alphaleft != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(11, this->_internal_alphaleft(), target);
  }

  // double BetaLeft = 12;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_betaleft = this->_internal_betaleft();
  uint64_t raw_betaleft;
  memcpy(&raw_betaleft, &tmp_betaleft, sizeof(tmp_betaleft));
  if (raw_betaleft != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(12, this->_internal_betaleft(), target);
  }

  // double AlphaRight = 13;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alpharight = this->_internal_alpharight();
  uint64_t raw_alpharight;
  memcpy(&raw_alpharight, &tmp_alpharight, sizeof(tmp_alpharight));
  if (raw_alpharight != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(13, this->_internal_alpharight(), target);
  }

  // double BetaRight = 14;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_betaright = this->_internal_betaright();
  uint64_t raw_betaright;
  memcpy(&raw_betaright, &tmp_betaright, sizeof(tmp_betaright));
  if (raw_betaright != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(14, this->_internal_betaright(), target);
  }

  // bool BordersAvailable = 15;
  if (this->_internal_bordersavailable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(15, this->_internal_bordersavailable(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PFDESolver.TSolverConfig)
  return target;
}

size_t TSolverConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PFDESolver.TSolverConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 SpaceCount = 1;
  if (this->_internal_spacecount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_spacecount());
  }

  // uint64 TimeCount = 2;
  if (this->_internal_timecount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timecount());
  }

  // double LeftBound = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_leftbound = this->_internal_leftbound();
  uint64_t raw_leftbound;
  memcpy(&raw_leftbound, &tmp_leftbound, sizeof(tmp_leftbound));
  if (raw_leftbound != 0) {
    total_size += 1 + 8;
  }

  // double RightBound = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_rightbound = this->_internal_rightbound();
  uint64_t raw_rightbound;
  memcpy(&raw_rightbound, &tmp_rightbound, sizeof(tmp_rightbound));
  if (raw_rightbound != 0) {
    total_size += 1 + 8;
  }

  // double MaxTime = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_maxtime = this->_internal_maxtime();
  uint64_t raw_maxtime;
  memcpy(&raw_maxtime, &tmp_maxtime, sizeof(tmp_maxtime));
  if (raw_maxtime != 0) {
    total_size += 1 + 8;
  }

  // double Alpha = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alpha = this->_internal_alpha();
  uint64_t raw_alpha;
  memcpy(&raw_alpha, &tmp_alpha, sizeof(tmp_alpha));
  if (raw_alpha != 0) {
    total_size += 1 + 8;
  }

  // double Gamma = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_gamma = this->_internal_gamma();
  uint64_t raw_gamma;
  memcpy(&raw_gamma, &tmp_gamma, sizeof(tmp_gamma));
  if (raw_gamma != 0) {
    total_size += 1 + 8;
  }

  // double SpaceStep = 8;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_spacestep = this->_internal_spacestep();
  uint64_t raw_spacestep;
  memcpy(&raw_spacestep, &tmp_spacestep, sizeof(tmp_spacestep));
  if (raw_spacestep != 0) {
    total_size += 1 + 8;
  }

  // double TimeStep = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_timestep = this->_internal_timestep();
  uint64_t raw_timestep;
  memcpy(&raw_timestep, &tmp_timestep, sizeof(tmp_timestep));
  if (raw_timestep != 0) {
    total_size += 1 + 8;
  }

  // double Beta = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_beta = this->_internal_beta();
  uint64_t raw_beta;
  memcpy(&raw_beta, &tmp_beta, sizeof(tmp_beta));
  if (raw_beta != 0) {
    total_size += 1 + 8;
  }

  // double AlphaLeft = 11;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alphaleft = this->_internal_alphaleft();
  uint64_t raw_alphaleft;
  memcpy(&raw_alphaleft, &tmp_alphaleft, sizeof(tmp_alphaleft));
  if (raw_alphaleft != 0) {
    total_size += 1 + 8;
  }

  // double BetaLeft = 12;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_betaleft = this->_internal_betaleft();
  uint64_t raw_betaleft;
  memcpy(&raw_betaleft, &tmp_betaleft, sizeof(tmp_betaleft));
  if (raw_betaleft != 0) {
    total_size += 1 + 8;
  }

  // double AlphaRight = 13;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alpharight = this->_internal_alpharight();
  uint64_t raw_alpharight;
  memcpy(&raw_alpharight, &tmp_alpharight, sizeof(tmp_alpharight));
  if (raw_alpharight != 0) {
    total_size += 1 + 8;
  }

  // double BetaRight = 14;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_betaright = this->_internal_betaright();
  uint64_t raw_betaright;
  memcpy(&raw_betaright, &tmp_betaright, sizeof(tmp_betaright));
  if (raw_betaright != 0) {
    total_size += 1 + 8;
  }

  // bool BordersAvailable = 15;
  if (this->_internal_bordersavailable() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TSolverConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TSolverConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TSolverConfig::GetClassData() const { return &_class_data_; }


void TSolverConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TSolverConfig*>(&to_msg);
  auto& from = static_cast<const TSolverConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PFDESolver.TSolverConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_spacecount() != 0) {
    _this->_internal_set_spacecount(from._internal_spacecount());
  }
  if (from._internal_timecount() != 0) {
    _this->_internal_set_timecount(from._internal_timecount());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_leftbound = from._internal_leftbound();
  uint64_t raw_leftbound;
  memcpy(&raw_leftbound, &tmp_leftbound, sizeof(tmp_leftbound));
  if (raw_leftbound != 0) {
    _this->_internal_set_leftbound(from._internal_leftbound());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_rightbound = from._internal_rightbound();
  uint64_t raw_rightbound;
  memcpy(&raw_rightbound, &tmp_rightbound, sizeof(tmp_rightbound));
  if (raw_rightbound != 0) {
    _this->_internal_set_rightbound(from._internal_rightbound());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_maxtime = from._internal_maxtime();
  uint64_t raw_maxtime;
  memcpy(&raw_maxtime, &tmp_maxtime, sizeof(tmp_maxtime));
  if (raw_maxtime != 0) {
    _this->_internal_set_maxtime(from._internal_maxtime());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alpha = from._internal_alpha();
  uint64_t raw_alpha;
  memcpy(&raw_alpha, &tmp_alpha, sizeof(tmp_alpha));
  if (raw_alpha != 0) {
    _this->_internal_set_alpha(from._internal_alpha());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_gamma = from._internal_gamma();
  uint64_t raw_gamma;
  memcpy(&raw_gamma, &tmp_gamma, sizeof(tmp_gamma));
  if (raw_gamma != 0) {
    _this->_internal_set_gamma(from._internal_gamma());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_spacestep = from._internal_spacestep();
  uint64_t raw_spacestep;
  memcpy(&raw_spacestep, &tmp_spacestep, sizeof(tmp_spacestep));
  if (raw_spacestep != 0) {
    _this->_internal_set_spacestep(from._internal_spacestep());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_timestep = from._internal_timestep();
  uint64_t raw_timestep;
  memcpy(&raw_timestep, &tmp_timestep, sizeof(tmp_timestep));
  if (raw_timestep != 0) {
    _this->_internal_set_timestep(from._internal_timestep());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_beta = from._internal_beta();
  uint64_t raw_beta;
  memcpy(&raw_beta, &tmp_beta, sizeof(tmp_beta));
  if (raw_beta != 0) {
    _this->_internal_set_beta(from._internal_beta());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alphaleft = from._internal_alphaleft();
  uint64_t raw_alphaleft;
  memcpy(&raw_alphaleft, &tmp_alphaleft, sizeof(tmp_alphaleft));
  if (raw_alphaleft != 0) {
    _this->_internal_set_alphaleft(from._internal_alphaleft());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_betaleft = from._internal_betaleft();
  uint64_t raw_betaleft;
  memcpy(&raw_betaleft, &tmp_betaleft, sizeof(tmp_betaleft));
  if (raw_betaleft != 0) {
    _this->_internal_set_betaleft(from._internal_betaleft());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_alpharight = from._internal_alpharight();
  uint64_t raw_alpharight;
  memcpy(&raw_alpharight, &tmp_alpharight, sizeof(tmp_alpharight));
  if (raw_alpharight != 0) {
    _this->_internal_set_alpharight(from._internal_alpharight());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_betaright = from._internal_betaright();
  uint64_t raw_betaright;
  memcpy(&raw_betaright, &tmp_betaright, sizeof(tmp_betaright));
  if (raw_betaright != 0) {
    _this->_internal_set_betaright(from._internal_betaright());
  }
  if (from._internal_bordersavailable() != 0) {
    _this->_internal_set_bordersavailable(from._internal_bordersavailable());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TSolverConfig::CopyFrom(const TSolverConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PFDESolver.TSolverConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TSolverConfig::IsInitialized() const {
  return true;
}

void TSolverConfig::InternalSwap(TSolverConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TSolverConfig, _impl_.bordersavailable_)
      + sizeof(TSolverConfig::_impl_.bordersavailable_)
      - PROTOBUF_FIELD_OFFSET(TSolverConfig, _impl_.spacecount_)>(
          reinterpret_cast<char*>(&_impl_.spacecount_),
          reinterpret_cast<char*>(&other->_impl_.spacecount_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TSolverConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_config_2eproto_getter, &descriptor_table_config_2eproto_once,
      file_level_metadata_config_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace PFDESolver
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PFDESolver::TSolverConfig*
Arena::CreateMaybeMessage< ::PFDESolver::TSolverConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PFDESolver::TSolverConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
