// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_config_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_config_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_config_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_config_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_config_2eproto;
namespace PFDESolver {
class TSolverConfig;
struct TSolverConfigDefaultTypeInternal;
extern TSolverConfigDefaultTypeInternal _TSolverConfig_default_instance_;
}  // namespace PFDESolver
PROTOBUF_NAMESPACE_OPEN
template<> ::PFDESolver::TSolverConfig* Arena::CreateMaybeMessage<::PFDESolver::TSolverConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PFDESolver {

// ===================================================================

class TSolverConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PFDESolver.TSolverConfig) */ {
 public:
  inline TSolverConfig() : TSolverConfig(nullptr) {}
  ~TSolverConfig() override;
  explicit PROTOBUF_CONSTEXPR TSolverConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TSolverConfig(const TSolverConfig& from);
  TSolverConfig(TSolverConfig&& from) noexcept
    : TSolverConfig() {
    *this = ::std::move(from);
  }

  inline TSolverConfig& operator=(const TSolverConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline TSolverConfig& operator=(TSolverConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TSolverConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const TSolverConfig* internal_default_instance() {
    return reinterpret_cast<const TSolverConfig*>(
               &_TSolverConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TSolverConfig& a, TSolverConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(TSolverConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TSolverConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TSolverConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TSolverConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TSolverConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TSolverConfig& from) {
    TSolverConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TSolverConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PFDESolver.TSolverConfig";
  }
  protected:
  explicit TSolverConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpaceCountFieldNumber = 1,
    kTimeCountFieldNumber = 2,
    kLeftBoundFieldNumber = 3,
    kRightBoundFieldNumber = 4,
    kMaxTimeFieldNumber = 5,
    kAlphaFieldNumber = 6,
    kGammaFieldNumber = 7,
    kSpaceStepFieldNumber = 8,
    kTimeStepFieldNumber = 9,
    kBetaFieldNumber = 10,
    kAlphaLeftFieldNumber = 11,
    kBetaLeftFieldNumber = 12,
    kAlphaRightFieldNumber = 13,
    kBetaRightFieldNumber = 14,
    kBordersAvailableFieldNumber = 15,
  };
  // uint64 SpaceCount = 1;
  void clear_spacecount();
  uint64_t spacecount() const;
  void set_spacecount(uint64_t value);
  private:
  uint64_t _internal_spacecount() const;
  void _internal_set_spacecount(uint64_t value);
  public:

  // uint64 TimeCount = 2;
  void clear_timecount();
  uint64_t timecount() const;
  void set_timecount(uint64_t value);
  private:
  uint64_t _internal_timecount() const;
  void _internal_set_timecount(uint64_t value);
  public:

  // double LeftBound = 3;
  void clear_leftbound();
  double leftbound() const;
  void set_leftbound(double value);
  private:
  double _internal_leftbound() const;
  void _internal_set_leftbound(double value);
  public:

  // double RightBound = 4;
  void clear_rightbound();
  double rightbound() const;
  void set_rightbound(double value);
  private:
  double _internal_rightbound() const;
  void _internal_set_rightbound(double value);
  public:

  // double MaxTime = 5;
  void clear_maxtime();
  double maxtime() const;
  void set_maxtime(double value);
  private:
  double _internal_maxtime() const;
  void _internal_set_maxtime(double value);
  public:

  // double Alpha = 6;
  void clear_alpha();
  double alpha() const;
  void set_alpha(double value);
  private:
  double _internal_alpha() const;
  void _internal_set_alpha(double value);
  public:

  // double Gamma = 7;
  void clear_gamma();
  double gamma() const;
  void set_gamma(double value);
  private:
  double _internal_gamma() const;
  void _internal_set_gamma(double value);
  public:

  // double SpaceStep = 8;
  void clear_spacestep();
  double spacestep() const;
  void set_spacestep(double value);
  private:
  double _internal_spacestep() const;
  void _internal_set_spacestep(double value);
  public:

  // double TimeStep = 9;
  void clear_timestep();
  double timestep() const;
  void set_timestep(double value);
  private:
  double _internal_timestep() const;
  void _internal_set_timestep(double value);
  public:

  // double Beta = 10;
  void clear_beta();
  double beta() const;
  void set_beta(double value);
  private:
  double _internal_beta() const;
  void _internal_set_beta(double value);
  public:

  // double AlphaLeft = 11;
  void clear_alphaleft();
  double alphaleft() const;
  void set_alphaleft(double value);
  private:
  double _internal_alphaleft() const;
  void _internal_set_alphaleft(double value);
  public:

  // double BetaLeft = 12;
  void clear_betaleft();
  double betaleft() const;
  void set_betaleft(double value);
  private:
  double _internal_betaleft() const;
  void _internal_set_betaleft(double value);
  public:

  // double AlphaRight = 13;
  void clear_alpharight();
  double alpharight() const;
  void set_alpharight(double value);
  private:
  double _internal_alpharight() const;
  void _internal_set_alpharight(double value);
  public:

  // double BetaRight = 14;
  void clear_betaright();
  double betaright() const;
  void set_betaright(double value);
  private:
  double _internal_betaright() const;
  void _internal_set_betaright(double value);
  public:

  // bool BordersAvailable = 15;
  void clear_bordersavailable();
  bool bordersavailable() const;
  void set_bordersavailable(bool value);
  private:
  bool _internal_bordersavailable() const;
  void _internal_set_bordersavailable(bool value);
  public:

  // @@protoc_insertion_point(class_scope:PFDESolver.TSolverConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t spacecount_;
    uint64_t timecount_;
    double leftbound_;
    double rightbound_;
    double maxtime_;
    double alpha_;
    double gamma_;
    double spacestep_;
    double timestep_;
    double beta_;
    double alphaleft_;
    double betaleft_;
    double alpharight_;
    double betaright_;
    bool bordersavailable_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TSolverConfig

// uint64 SpaceCount = 1;
inline void TSolverConfig::clear_spacecount() {
  _impl_.spacecount_ = uint64_t{0u};
}
inline uint64_t TSolverConfig::_internal_spacecount() const {
  return _impl_.spacecount_;
}
inline uint64_t TSolverConfig::spacecount() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.SpaceCount)
  return _internal_spacecount();
}
inline void TSolverConfig::_internal_set_spacecount(uint64_t value) {
  
  _impl_.spacecount_ = value;
}
inline void TSolverConfig::set_spacecount(uint64_t value) {
  _internal_set_spacecount(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.SpaceCount)
}

// uint64 TimeCount = 2;
inline void TSolverConfig::clear_timecount() {
  _impl_.timecount_ = uint64_t{0u};
}
inline uint64_t TSolverConfig::_internal_timecount() const {
  return _impl_.timecount_;
}
inline uint64_t TSolverConfig::timecount() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.TimeCount)
  return _internal_timecount();
}
inline void TSolverConfig::_internal_set_timecount(uint64_t value) {
  
  _impl_.timecount_ = value;
}
inline void TSolverConfig::set_timecount(uint64_t value) {
  _internal_set_timecount(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.TimeCount)
}

// double LeftBound = 3;
inline void TSolverConfig::clear_leftbound() {
  _impl_.leftbound_ = 0;
}
inline double TSolverConfig::_internal_leftbound() const {
  return _impl_.leftbound_;
}
inline double TSolverConfig::leftbound() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.LeftBound)
  return _internal_leftbound();
}
inline void TSolverConfig::_internal_set_leftbound(double value) {
  
  _impl_.leftbound_ = value;
}
inline void TSolverConfig::set_leftbound(double value) {
  _internal_set_leftbound(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.LeftBound)
}

// double RightBound = 4;
inline void TSolverConfig::clear_rightbound() {
  _impl_.rightbound_ = 0;
}
inline double TSolverConfig::_internal_rightbound() const {
  return _impl_.rightbound_;
}
inline double TSolverConfig::rightbound() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.RightBound)
  return _internal_rightbound();
}
inline void TSolverConfig::_internal_set_rightbound(double value) {
  
  _impl_.rightbound_ = value;
}
inline void TSolverConfig::set_rightbound(double value) {
  _internal_set_rightbound(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.RightBound)
}

// double MaxTime = 5;
inline void TSolverConfig::clear_maxtime() {
  _impl_.maxtime_ = 0;
}
inline double TSolverConfig::_internal_maxtime() const {
  return _impl_.maxtime_;
}
inline double TSolverConfig::maxtime() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.MaxTime)
  return _internal_maxtime();
}
inline void TSolverConfig::_internal_set_maxtime(double value) {
  
  _impl_.maxtime_ = value;
}
inline void TSolverConfig::set_maxtime(double value) {
  _internal_set_maxtime(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.MaxTime)
}

// double Alpha = 6;
inline void TSolverConfig::clear_alpha() {
  _impl_.alpha_ = 0;
}
inline double TSolverConfig::_internal_alpha() const {
  return _impl_.alpha_;
}
inline double TSolverConfig::alpha() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.Alpha)
  return _internal_alpha();
}
inline void TSolverConfig::_internal_set_alpha(double value) {
  
  _impl_.alpha_ = value;
}
inline void TSolverConfig::set_alpha(double value) {
  _internal_set_alpha(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.Alpha)
}

// double Gamma = 7;
inline void TSolverConfig::clear_gamma() {
  _impl_.gamma_ = 0;
}
inline double TSolverConfig::_internal_gamma() const {
  return _impl_.gamma_;
}
inline double TSolverConfig::gamma() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.Gamma)
  return _internal_gamma();
}
inline void TSolverConfig::_internal_set_gamma(double value) {
  
  _impl_.gamma_ = value;
}
inline void TSolverConfig::set_gamma(double value) {
  _internal_set_gamma(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.Gamma)
}

// double SpaceStep = 8;
inline void TSolverConfig::clear_spacestep() {
  _impl_.spacestep_ = 0;
}
inline double TSolverConfig::_internal_spacestep() const {
  return _impl_.spacestep_;
}
inline double TSolverConfig::spacestep() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.SpaceStep)
  return _internal_spacestep();
}
inline void TSolverConfig::_internal_set_spacestep(double value) {
  
  _impl_.spacestep_ = value;
}
inline void TSolverConfig::set_spacestep(double value) {
  _internal_set_spacestep(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.SpaceStep)
}

// double TimeStep = 9;
inline void TSolverConfig::clear_timestep() {
  _impl_.timestep_ = 0;
}
inline double TSolverConfig::_internal_timestep() const {
  return _impl_.timestep_;
}
inline double TSolverConfig::timestep() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.TimeStep)
  return _internal_timestep();
}
inline void TSolverConfig::_internal_set_timestep(double value) {
  
  _impl_.timestep_ = value;
}
inline void TSolverConfig::set_timestep(double value) {
  _internal_set_timestep(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.TimeStep)
}

// double Beta = 10;
inline void TSolverConfig::clear_beta() {
  _impl_.beta_ = 0;
}
inline double TSolverConfig::_internal_beta() const {
  return _impl_.beta_;
}
inline double TSolverConfig::beta() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.Beta)
  return _internal_beta();
}
inline void TSolverConfig::_internal_set_beta(double value) {
  
  _impl_.beta_ = value;
}
inline void TSolverConfig::set_beta(double value) {
  _internal_set_beta(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.Beta)
}

// double AlphaLeft = 11;
inline void TSolverConfig::clear_alphaleft() {
  _impl_.alphaleft_ = 0;
}
inline double TSolverConfig::_internal_alphaleft() const {
  return _impl_.alphaleft_;
}
inline double TSolverConfig::alphaleft() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.AlphaLeft)
  return _internal_alphaleft();
}
inline void TSolverConfig::_internal_set_alphaleft(double value) {
  
  _impl_.alphaleft_ = value;
}
inline void TSolverConfig::set_alphaleft(double value) {
  _internal_set_alphaleft(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.AlphaLeft)
}

// double BetaLeft = 12;
inline void TSolverConfig::clear_betaleft() {
  _impl_.betaleft_ = 0;
}
inline double TSolverConfig::_internal_betaleft() const {
  return _impl_.betaleft_;
}
inline double TSolverConfig::betaleft() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.BetaLeft)
  return _internal_betaleft();
}
inline void TSolverConfig::_internal_set_betaleft(double value) {
  
  _impl_.betaleft_ = value;
}
inline void TSolverConfig::set_betaleft(double value) {
  _internal_set_betaleft(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.BetaLeft)
}

// double AlphaRight = 13;
inline void TSolverConfig::clear_alpharight() {
  _impl_.alpharight_ = 0;
}
inline double TSolverConfig::_internal_alpharight() const {
  return _impl_.alpharight_;
}
inline double TSolverConfig::alpharight() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.AlphaRight)
  return _internal_alpharight();
}
inline void TSolverConfig::_internal_set_alpharight(double value) {
  
  _impl_.alpharight_ = value;
}
inline void TSolverConfig::set_alpharight(double value) {
  _internal_set_alpharight(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.AlphaRight)
}

// double BetaRight = 14;
inline void TSolverConfig::clear_betaright() {
  _impl_.betaright_ = 0;
}
inline double TSolverConfig::_internal_betaright() const {
  return _impl_.betaright_;
}
inline double TSolverConfig::betaright() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.BetaRight)
  return _internal_betaright();
}
inline void TSolverConfig::_internal_set_betaright(double value) {
  
  _impl_.betaright_ = value;
}
inline void TSolverConfig::set_betaright(double value) {
  _internal_set_betaright(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.BetaRight)
}

// bool BordersAvailable = 15;
inline void TSolverConfig::clear_bordersavailable() {
  _impl_.bordersavailable_ = false;
}
inline bool TSolverConfig::_internal_bordersavailable() const {
  return _impl_.bordersavailable_;
}
inline bool TSolverConfig::bordersavailable() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TSolverConfig.BordersAvailable)
  return _internal_bordersavailable();
}
inline void TSolverConfig::_internal_set_bordersavailable(bool value) {
  
  _impl_.bordersavailable_ = value;
}
inline void TSolverConfig::set_bordersavailable(bool value) {
  _internal_set_bordersavailable(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TSolverConfig.BordersAvailable)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PFDESolver

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_config_2eproto
