version: '3'

services:
  web-server:
    container_name: WebServer
    build: core/client/
    command: python ./client.py --host 0.0.0.0
    ports: 
      - 13000:8002
    environment:
      - PYTHONPATH=libs/generated
