// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

#include "matrix.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace PFDESolver {
PROTOBUF_CONSTEXPR TMatrix::TMatrix(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_.rows_)*/uint64_t{0u}
  , /*decltype(_impl_.columns_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TMatrixDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TMatrixDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TMatrixDefaultTypeInternal() {}
  union {
    TMatrix _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TMatrixDefaultTypeInternal _TMatrix_default_instance_;
}  // namespace PFDESolver
static ::_pb::Metadata file_level_metadata_matrix_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_matrix_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_matrix_2eproto = nullptr;

const uint32_t TableStruct_matrix_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TMatrix, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TMatrix, _impl_.rows_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TMatrix, _impl_.columns_),
  PROTOBUF_FIELD_OFFSET(::PFDESolver::TMatrix, _impl_.data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::PFDESolver::TMatrix)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::PFDESolver::_TMatrix_default_instance_._instance,
};

const char descriptor_table_protodef_matrix_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014matrix.proto\022\nPFDESolver\"6\n\007TMatrix\022\014\n"
  "\004Rows\030\001 \001(\004\022\017\n\007Columns\030\002 \001(\004\022\014\n\004Data\030\003 \003"
  "(\001B\024Z\022/pfdesolver_protosb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_matrix_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_matrix_2eproto = {
    false, false, 112, descriptor_table_protodef_matrix_2eproto,
    "matrix.proto",
    &descriptor_table_matrix_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_matrix_2eproto::offsets,
    file_level_metadata_matrix_2eproto, file_level_enum_descriptors_matrix_2eproto,
    file_level_service_descriptors_matrix_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_matrix_2eproto_getter() {
  return &descriptor_table_matrix_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_matrix_2eproto(&descriptor_table_matrix_2eproto);
namespace PFDESolver {

// ===================================================================

class TMatrix::_Internal {
 public:
};

TMatrix::TMatrix(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PFDESolver.TMatrix)
}
TMatrix::TMatrix(const TMatrix& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TMatrix* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , decltype(_impl_.rows_){}
    , decltype(_impl_.columns_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.rows_, &from._impl_.rows_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.columns_) -
    reinterpret_cast<char*>(&_impl_.rows_)) + sizeof(_impl_.columns_));
  // @@protoc_insertion_point(copy_constructor:PFDESolver.TMatrix)
}

inline void TMatrix::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , decltype(_impl_.rows_){uint64_t{0u}}
    , decltype(_impl_.columns_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TMatrix::~TMatrix() {
  // @@protoc_insertion_point(destructor:PFDESolver.TMatrix)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TMatrix::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedField();
}

void TMatrix::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TMatrix::Clear() {
// @@protoc_insertion_point(message_clear_start:PFDESolver.TMatrix)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  ::memset(&_impl_.rows_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.columns_) -
      reinterpret_cast<char*>(&_impl_.rows_)) + sizeof(_impl_.columns_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TMatrix::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 Rows = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.rows_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 Columns = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.columns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated double Data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 25) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TMatrix::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PFDESolver.TMatrix)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 Rows = 1;
  if (this->_internal_rows() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_rows(), target);
  }

  // uint64 Columns = 2;
  if (this->_internal_columns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_columns(), target);
  }

  // repeated double Data = 3;
  if (this->_internal_data_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PFDESolver.TMatrix)
  return target;
}

size_t TMatrix::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PFDESolver.TMatrix)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double Data = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // uint64 Rows = 1;
  if (this->_internal_rows() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_rows());
  }

  // uint64 Columns = 2;
  if (this->_internal_columns() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_columns());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TMatrix::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TMatrix::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TMatrix::GetClassData() const { return &_class_data_; }


void TMatrix::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TMatrix*>(&to_msg);
  auto& from = static_cast<const TMatrix&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PFDESolver.TMatrix)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  if (from._internal_rows() != 0) {
    _this->_internal_set_rows(from._internal_rows());
  }
  if (from._internal_columns() != 0) {
    _this->_internal_set_columns(from._internal_columns());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TMatrix::CopyFrom(const TMatrix& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PFDESolver.TMatrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TMatrix::IsInitialized() const {
  return true;
}

void TMatrix::InternalSwap(TMatrix* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TMatrix, _impl_.columns_)
      + sizeof(TMatrix::_impl_.columns_)
      - PROTOBUF_FIELD_OFFSET(TMatrix, _impl_.rows_)>(
          reinterpret_cast<char*>(&_impl_.rows_),
          reinterpret_cast<char*>(&other->_impl_.rows_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TMatrix::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_matrix_2eproto_getter, &descriptor_table_matrix_2eproto_once,
      file_level_metadata_matrix_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace PFDESolver
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PFDESolver::TMatrix*
Arena::CreateMaybeMessage< ::PFDESolver::TMatrix >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PFDESolver::TMatrix >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
