// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_matrix_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_matrix_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_matrix_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_matrix_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_matrix_2eproto;
namespace PFDESolver {
class TMatrix;
struct TMatrixDefaultTypeInternal;
extern TMatrixDefaultTypeInternal _TMatrix_default_instance_;
}  // namespace PFDESolver
PROTOBUF_NAMESPACE_OPEN
template<> ::PFDESolver::TMatrix* Arena::CreateMaybeMessage<::PFDESolver::TMatrix>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PFDESolver {

// ===================================================================

class TMatrix final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PFDESolver.TMatrix) */ {
 public:
  inline TMatrix() : TMatrix(nullptr) {}
  ~TMatrix() override;
  explicit PROTOBUF_CONSTEXPR TMatrix(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TMatrix(const TMatrix& from);
  TMatrix(TMatrix&& from) noexcept
    : TMatrix() {
    *this = ::std::move(from);
  }

  inline TMatrix& operator=(const TMatrix& from) {
    CopyFrom(from);
    return *this;
  }
  inline TMatrix& operator=(TMatrix&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TMatrix& default_instance() {
    return *internal_default_instance();
  }
  static inline const TMatrix* internal_default_instance() {
    return reinterpret_cast<const TMatrix*>(
               &_TMatrix_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TMatrix& a, TMatrix& b) {
    a.Swap(&b);
  }
  inline void Swap(TMatrix* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TMatrix* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TMatrix* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TMatrix>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TMatrix& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TMatrix& from) {
    TMatrix::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TMatrix* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PFDESolver.TMatrix";
  }
  protected:
  explicit TMatrix(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kRowsFieldNumber = 1,
    kColumnsFieldNumber = 2,
  };
  // repeated double Data = 3;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  double _internal_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_data() const;
  void _internal_add_data(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_data();
  public:
  double data(int index) const;
  void set_data(int index, double value);
  void add_data(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_data();

  // uint64 Rows = 1;
  void clear_rows();
  uint64_t rows() const;
  void set_rows(uint64_t value);
  private:
  uint64_t _internal_rows() const;
  void _internal_set_rows(uint64_t value);
  public:

  // uint64 Columns = 2;
  void clear_columns();
  uint64_t columns() const;
  void set_columns(uint64_t value);
  private:
  uint64_t _internal_columns() const;
  void _internal_set_columns(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:PFDESolver.TMatrix)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > data_;
    uint64_t rows_;
    uint64_t columns_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matrix_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TMatrix

// uint64 Rows = 1;
inline void TMatrix::clear_rows() {
  _impl_.rows_ = uint64_t{0u};
}
inline uint64_t TMatrix::_internal_rows() const {
  return _impl_.rows_;
}
inline uint64_t TMatrix::rows() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TMatrix.Rows)
  return _internal_rows();
}
inline void TMatrix::_internal_set_rows(uint64_t value) {
  
  _impl_.rows_ = value;
}
inline void TMatrix::set_rows(uint64_t value) {
  _internal_set_rows(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TMatrix.Rows)
}

// uint64 Columns = 2;
inline void TMatrix::clear_columns() {
  _impl_.columns_ = uint64_t{0u};
}
inline uint64_t TMatrix::_internal_columns() const {
  return _impl_.columns_;
}
inline uint64_t TMatrix::columns() const {
  // @@protoc_insertion_point(field_get:PFDESolver.TMatrix.Columns)
  return _internal_columns();
}
inline void TMatrix::_internal_set_columns(uint64_t value) {
  
  _impl_.columns_ = value;
}
inline void TMatrix::set_columns(uint64_t value) {
  _internal_set_columns(value);
  // @@protoc_insertion_point(field_set:PFDESolver.TMatrix.Columns)
}

// repeated double Data = 3;
inline int TMatrix::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int TMatrix::data_size() const {
  return _internal_data_size();
}
inline void TMatrix::clear_data() {
  _impl_.data_.Clear();
}
inline double TMatrix::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline double TMatrix::data(int index) const {
  // @@protoc_insertion_point(field_get:PFDESolver.TMatrix.Data)
  return _internal_data(index);
}
inline void TMatrix::set_data(int index, double value) {
  _impl_.data_.Set(index, value);
  // @@protoc_insertion_point(field_set:PFDESolver.TMatrix.Data)
}
inline void TMatrix::_internal_add_data(double value) {
  _impl_.data_.Add(value);
}
inline void TMatrix::add_data(double value) {
  _internal_add_data(value);
  // @@protoc_insertion_point(field_add:PFDESolver.TMatrix.Data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TMatrix::_internal_data() const {
  return _impl_.data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
TMatrix::data() const {
  // @@protoc_insertion_point(field_list:PFDESolver.TMatrix.Data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TMatrix::_internal_mutable_data() {
  return &_impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
TMatrix::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:PFDESolver.TMatrix.Data)
  return _internal_mutable_data();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PFDESolver

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_matrix_2eproto
