// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: server.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TFDESolverServer_RunTask_FullMethodName = "/PFDESolverServer.TFDESolverServer/RunTask"
)

// TFDESolverServerClient is the client API for TFDESolverServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TFDESolverServerClient interface {
	RunTask(ctx context.Context, in *TClientConfig, opts ...grpc.CallOption) (*TResults, error)
}

type tFDESolverServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTFDESolverServerClient(cc grpc.ClientConnInterface) TFDESolverServerClient {
	return &tFDESolverServerClient{cc}
}

func (c *tFDESolverServerClient) RunTask(ctx context.Context, in *TClientConfig, opts ...grpc.CallOption) (*TResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TResults)
	err := c.cc.Invoke(ctx, TFDESolverServer_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TFDESolverServerServer is the server API for TFDESolverServer service.
// All implementations must embed UnimplementedTFDESolverServerServer
// for forward compatibility.
type TFDESolverServerServer interface {
	RunTask(context.Context, *TClientConfig) (*TResults, error)
	mustEmbedUnimplementedTFDESolverServerServer()
}

// UnimplementedTFDESolverServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTFDESolverServerServer struct{}

func (UnimplementedTFDESolverServerServer) RunTask(context.Context, *TClientConfig) (*TResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedTFDESolverServerServer) mustEmbedUnimplementedTFDESolverServerServer() {}
func (UnimplementedTFDESolverServerServer) testEmbeddedByValue()                          {}

// UnsafeTFDESolverServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TFDESolverServerServer will
// result in compilation errors.
type UnsafeTFDESolverServerServer interface {
	mustEmbedUnimplementedTFDESolverServerServer()
}

func RegisterTFDESolverServerServer(s grpc.ServiceRegistrar, srv TFDESolverServerServer) {
	// If the following call pancis, it indicates UnimplementedTFDESolverServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TFDESolverServer_ServiceDesc, srv)
}

func _TFDESolverServer_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TClientConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TFDESolverServerServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TFDESolverServer_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TFDESolverServerServer).RunTask(ctx, req.(*TClientConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// TFDESolverServer_ServiceDesc is the grpc.ServiceDesc for TFDESolverServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TFDESolverServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PFDESolverServer.TFDESolverServer",
	HandlerType: (*TFDESolverServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunTask",
			Handler:    _TFDESolverServer_RunTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
