# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatrix.proto\x12\nPFDESolver\"6\n\x07TMatrix\x12\x0c\n\x04Rows\x18\x01 \x01(\x04\x12\x0f\n\x07\x43olumns\x18\x02 \x01(\x04\x12\x0c\n\x04\x44\x61ta\x18\x03 \x03(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TMATRIX._serialized_start=28
  _TMATRIX._serialized_end=82
# @@protoc_insertion_point(module_scope)
